use serbuffer_gen::{Codegen, DataType::*};

fn main() {
    Codegen::new("src/buffer_gen", "TlbDetail")
        .field("st", U64)
        .field("unix_timestamp", U64)
        .field("ip", STRING)
        .field("status", I32)
        .field("up_addr", STRING)
        .field("up_status", I32)
        .field("user", STRING)
        .field("reqbody", STRING)
        .field("referer", STRING)
        .field("ua", STRING)
        .field("byte", I32)
        .field("forwarded", STRING)
        .field("timeuse", F64)
        .field("upstream_response_time", F64)
        .field("request_time", F64)
        .field("server_name", STRING)
        .field("host", STRING)
        .field("hostname", STRING)
        .field("server_protocol", STRING)
        .field("request_method", STRING)
        .field("request_uri", STRING)
        .field("request_parameter", STRING)
        .field("bytes_recv", I64)
        .field("bytes_sent", I64)
        .field("gzip_ratio", F64)
        .field("sent_http_tid", STRING)
        .field("sent_http_rid", STRING)
        .field("sent_http_uid", STRING)
        .field("scheme", STRING)
        .field("remote_port", I64)
        .field("content_length", I64)
        .field("x_request_id", STRING)
        .field("csi", STRING)
        .field("crp", STRING)
        .field("content_type", STRING)
        .field("apmat", STRING)
        .field("location", STRING)
        .field("upstream_name", STRING)
        .field("client", STRING)
        .field("facility", U64)
        .field("priority", U64)
        .field("severity", U64)
        .field("tag", STRING)
        .field("logant_idc", STRING)
        .field("logant_type", STRING)
        .gen()
        .expect("buffer gen error");
}
